{% set name = "python-sounddevice" %}
{% set pypi_name = "sounddevice" %}
{% set version = "0.5.2" %}
{% set sha256 = "c634d51bd4e922d6f0fa5e1a975cc897c947f61d31da9f79ba7ea34dff448b49" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ pypi_name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/{{ pypi_name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  # noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - cffi
    - setuptools
  run:
    - python >={{ python_min }}
    - cffi
    - portaudio
    - numpy


test:
  requires:
    - python {{ python_min }}
  imports:
    - sounddevice

about:
  home: https://python-sounddevice.readthedocs.io/
  license: MIT
  license_family: MIT
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: Play and Record Sound with Python
  dev_url: https://github.com/spatialaudio/python-sounddevice/

extra:
  recipe-maintainers:
    - MementoRC
    - tyrius02
    - scopatz
