{% set name = "python-sounddevice" %}
{% set pypi_name = "sounddevice" %}
{% set version = "0.5.1" %}
{% set sha256 = "09ca991daeda8ce4be9ac91e15a9a81c8f81efa6b695a348c9171ea0c16cb041" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ pypi_name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/{{ pypi_name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - cffi
  run:
    - python >={{ python_min }}
    - cffi
    - portaudio
    - numpy


test:
  requires:
    - python {{ python_min }}
  imports:
    - sounddevice

about:
  home: https://python-sounddevice.readthedocs.io/
  license: MIT
  license_family: MIT
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: Play and Record Sound with Python
  dev_url: https://github.com/spatialaudio/python-sounddevice/

extra:
  recipe-maintainers:
    - MementoRC
    - tyrius02
    - scopatz
